#pragma once

#include <Windows.h>

BOOL setASLR(PIMAGE_OPTIONAL_HEADER Optional);
BOOL removeASLR(PIMAGE_OPTIONAL_HEADER Optional);
BOOL setDEP(PIMAGE_OPTIONAL_HEADER Optional);
BOOL removeDEP(PIMAGE_OPTIONAL_HEADER Optional);
BOOL setFINTEGRITY(PIMAGE_OPTIONAL_HEADER Optional);
BOOL removeFINTEGRITY(PIMAGE_OPTIONAL_HEADER Optional);